#pragma once
#define DISCOVERY_MAX_HOSTS 2048
#define DISCOVERY_MAX_SERVICES 2048
#define DISCOVERY_SMALL_NET_THRESHOLD 1024
#define DISCOVERY_WINDOW_SEED 128
#define DISCOVERY_WINDOW_EXPAND 4
#define MAX_SMART_TARGETS DISCOVERY_MAX_HOSTS
